import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

// Keep the exported city as source data; only its two woodland approaches are
// scaled into Hearthwood. The authored square, houses and story remain intact.
export function adaptWatabou(source) {
  const roads = source.features?.find(feature => feature.id === 'roads');
  if (roads?.type !== 'GeometryCollection' || roads.geometries.length < 2) throw new Error('Watabou roads are missing');
  return roads.geometries.slice(0, 2).map(road => {
    if (road.type !== 'LineString' || road.coordinates.length < 2) throw new Error('Invalid Watabou road');
    return [[8, 8], ...road.coordinates.map(point => {
      if (point.length !== 2 || !point.every(Number.isFinite)) throw new Error('Invalid Watabou coordinate');
      return point.map(value => Math.round(8 + value * .2));
    })];
  });
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const source = JSON.parse(readFileSync(new URL('../../public/maps/hearthwood-watabou.json', import.meta.url)));
  writeFileSync(new URL('./hearthwood-roads.js', import.meta.url), `// Generated by node scripts/maps/adapt-watabou.mjs; source: public/maps/hearthwood-watabou.json\nexport default ${JSON.stringify(adaptWatabou(source))};\n`);
}
