// Generated by node scripts/maps/adapt-watabou.mjs; source: public/maps/hearthwood-watabou.json
export default [[[8,8],[10,-1],[11,-6],[3,-20],[5,-29],[15,-34],[23,-39],[27,-46],[39,-59]],[[8,8],[-2,7],[-6,9],[-28,-4],[-55,-2]]];
